CREATE TABLE users
(
    id SERIAL PRIMARY KEY NOT NULL,
    name CHARACTER VARYING (100),
    lastname CHARACTER VARYING (100),
    email CHARACTER VARYING (100),
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);