CREATE TABLE images
(
    id SERIAL PRIMARY KEY NOT NULL,
    path CHARACTER VARYING (500) NOT NULL,
    main BOOLEAN DEFAULT FALSE,
    product_id INTEGER REFERENCES products(id),
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);